apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  template:
    spec:
      containers:
        - name: checkoutservice
          env:
            - name: SHIPPING_SERVICE_ADDR
              value: "local-shippingservice:50051"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "local-productcatalogservice:3550"
            - name: CART_SERVICE_ADDR
              value: "local-cartservice:7070"
            - name: CURRENCY_SERVICE_ADDR
              value: "local-currencyservice:7000"
            - name: EMAIL_SERVICE_ADDR
              value: "local-emailservice:8080"
            - name: PAYMENT_SERVICE_ADDR
              value: "local-paymentservice:50051"