apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - adservice.yml
 - cartservice.yaml
 - checkoutservice.yml
 - currencyservice.yml
 - emailservice.yml
 - frontend.yml
# - loadgenerator.yml # During development, the loadgenerator module inside skaffold.yml will be used.
 - paymentservice.yml
 - productcatalogservice.yml
 - recommendationservice.yml
 - shippingservice.yml