apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      serviceAccountName: productcatalogservice
      containers:
        - name: productcatalogservice
          image: productcatalogservice:1.0
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "3550"
          # Set environment variables for service addresses
            - name: "COLLECTOR_SERVICE_ADDR"
          # Set environment variables for application configuration
            - name: "ENABLE_TRACING"
            - name: "DISABLE_PROFILER"
              value: "1"
            - name: "EXTRA_LATENCY"
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            rgpc:
              port: 3550
              initialDelaySeconds: 20
              periodSeconds: 20
          livenessProbe:
            rgpc:
              port: 3550
              initialDelaySeconds: 20
              periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
spec:
  selector:
    app: productcatalogservice
  type: ClusterIP
  ports:
    - port: 3550
      targetPort: 3550
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice